### ISSUE TITLE
希望看完后你可以关闭这个评论

### ISSUE THREAD

**Issue by rcy1314** [SBsoft-Internet-Technology/Note-chat#1]
<img width="920" alt="1728127979145" src="https://github.com/user-attachments/assets/463f78b1-c990-4e75-b400-687185690d2c">
已说明所有，也指明了最开始的修改了AI改写，但这个项目我不会再涉及，也根本不是吵，原因在之前也提过，所有的文件都指向我的云服务器代码，在最初的版本，我甚至直接写的IP地址，但被xiaojiang233一味指责，所以后来又修改了，目前已完全删除，没有指明借鉴之处是我的错，在另一个评论中已说明过复刻过你的项目并借鉴过（已删），没有指明借鉴这是我的错和需要承认的，附上最后一次的文件所有，此后不会再涉及此类相关，感谢你

[jsdcdn.zip](https://github.com/user-attachments/files/17266038/jsdcdn.zip)

<img width="1122" alt="1728129319843" src="https://github.com/user-attachments/assets/fa46f55d-69af-4835-8104-f722af2b1556">

然后，我并没有恶俗，也希望你能看看自己的评论

**Comment by yanjie233** [comment]
你为什么要一直揪着Ai改写不放呢，你有没有想过是你使用了别人的代码而不表明出处。和Ai有什么关系。

**Comment by yanjie233** [comment]
还有能不能不要在各种各样的仓库下面拉屎，这是议题，不是评论区、留言板

**Comment by rcy1314** [comment]
<img width="833" alt="1728131274149" src="https://github.com/user-attachments/assets/d35c94a2-f321-48e9-8c17-d956e68fbaff">
我没有不承认借鉴吧！AI改写也可以不加，我不理解的是你目前完全超出了范畴，如果你觉得我的道歉不好，我也在你的发文中再次指出了，但我完全不理解你的评论，我尊重你，所以，没有过激

**Comment by rcy1314** [comment]
我也不是什么大佬，文件包也给了，也说明说只有最初的版本借鉴过
[jsdcdn.zip](https://github.com/user-attachments/files/17266177/jsdcdn.zip)

**Comment by rcy1314** [comment]
我再次道歉

**Comment by rong6** [comment]
> <img alt="1728131274149" width="833" src="https://private-user-images.githubusercontent.com/46085246/373871367-d35c94a2-f321-48e9-8c17-d956e68fbaff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMzE4NjIsIm5iZiI6MTcyODEzMTU2MiwicGF0aCI6Ii80NjA4NTI0Ni8zNzM4NzEzNjctZDM1Yzk0YTItZjMyMS00OGU5LThjMTctZDk1NmU2OGZiYWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDEyMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZjE1MTk0YWM3NDRiNzFhNDVkZGIyOTU1OGFkMmYxNjAxNjVkNDdiMWMwNDVhZTZhMmU5ZTNiMDdiNjlmMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tl_SgA5ntdVqrOUJ0kPFtlflAZaPI9EpSEEh4O4n1ag"> 我没有不承认借鉴吧！AI改写也可以不加，我不理解的是你目前完全超出了范畴，如果你觉得我的道歉不好，我也在你的发文中再次指出了，但我完全不理解你的评论，我尊重你，所以，没有过激

我已在博客回复了你的评论：
> 好了，事情到这里就结束了，因为前文是昨天写的所以语气不太友好，考虑不够全面，仅做存档，下次别做这种事就好了(；´д｀)ゞ
对于你截取的那一部分是我昨天写的，毕竟我看你也是写了个不错的个人主页，那个项目也有几百的star，所以当初认为你是“大佬”有问题吗。整篇文章中关于你的部分已经全部打码，别人也找不到你，你也不会丢脸，这件事就算过去了，OK？

**Comment by rcy1314** [comment]
@yanjie233 对不起，我从开始就不该借鉴，对不起，我不该让你拿着开源文化来做说明，但我没有攻击，也没有拿着项目做过多无味的事，我的改写和借鉴就是个错误的决定，但我并没有拿这个当理由，也希望不要曲解意思，这是我的回复，请你看清

**Comment by rcy1314** [comment]
<img width="825" alt="1728135424702" src="https://github.com/user-attachments/assets/7c899f90-c425-49da-a9a2-b3dd4afcf996">
这不是一个结束，而是我真的理解不了你们非要发文的用意，我也没有逃避，每次评论都会强调在改写时没有提及rong6是我个人的错误，我只是不想让事件不是结束的结束，这是我完全理解不了的，也是完全接受不了的

**Comment by rong6** [comment]
> <img alt="1728135424702" width="825" src="https://private-user-images.githubusercontent.com/46085246/373875380-7c899f90-c425-49da-a9a2-b3dd4afcf996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMzY4MDEsIm5iZiI6MTcyODEzNjUwMSwicGF0aCI6Ii80NjA4NTI0Ni8zNzM4NzUzODAtN2M4OTlmOTAtYzQyNS00OWRhLWE5YTItYjNkZDRhZmNmOTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDEzNTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MGJmODlhNzg2MDZhOGY5ZmRmMWJiNDdjNjY4ZjQ1ZDA1NjY0NWZkN2RkZjM0NDJiZjMwNDc2NjliYTRjZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.haEGyTvwxkIvZS5SPqi7hstG5z_WRToRKysvrm41umk"> 这不是一个结束，而是我真的理解不了你们非要发文的用意，我也没有逃避，每次评论都会强调在改写时没有提及rong6是我个人的错误，我只是不想让事件不是结束的结束，这是我完全理解不了的，也是完全接受不了的

博客已回复：
>关于你今日的评论已删除部分内容，但部分作为事实必须存在，我只是**在记录日常**，结尾是升华到整个开源社区，没有特意针对你。再提醒一遍，**你的所有信息我都没有透露，我已经全部打码**。 既然你是个成年人，那就应该知道自己在做什么，早知今日何必当初。你收藏过我，推荐过我，我很感谢，但就事论事，一码归一码，你在这件事上就是错的一塌糊涂，这件事就算这么结束了好吗？我会把你在这条文章下发的评论全部隐藏，这样除了这件事就只有包含你我总共4个人知道。

我今天晚上一直都在处理这件事，本来都还有其他更重要的事因此被耽搁了，这件事真的就这样结束吧，不要再浪费你我的时间了
